export default [
    {
        id: 1,
        senderId: 1,
        senderName: "Beyza",
        color: '#FF399C',
        message: "Anim quis nostru",
        time: "17:04",
        hasSenderName: false,
    },
    {
        id: 2,
        senderId: 1,
        senderName: "Beyza",
        color: '#FF399C',
        message: "Anim quis nostrud do consequat dolor minim ea esse nulla culpa non fugiat. Hey now how",
        time: "17:04",
        hasSenderName: true,
    },
    {
        id: 3,
        senderId: 2,
        senderName: "Beyza 2",
        color: '#93D033',
        message: "Anim quis nostrud do consequat dolor minim ea esse nulla culpa non fugiat",
        time: "17:04",
        hasSenderName: true,
    },
    {
        id: 4,
        senderId: 3,
        senderName: "Beyza 3",
        color: '#52E2D1',
        message: "Anim quis nostrud do consequat dolor minim ea esse nulla culpa non fugiat",
        time: "17:04",
        hasSenderName: false,
    },
    {
        id: 5,
        senderId: 3,
        senderName: "Beyza 3",
        color: '#52E2D1',
        message: "Anim quis nostrud do consequat dolor minim ea esse nulla culpa non fugiat",
        time: "17:04",
        hasSenderName: true,
    },
    {
        date: "16.04.2021",
    },
    {
        id: 6,
        senderId: 3,
        senderName: "Beyza 3",
        color: '#52E2D1',
        message: "Anim quis nostrud do consequat dolor minim ea esse nulla culpa non fugiat",
        time: "17:04",
        hasSenderName: true,
    },
    {
        id: 7,
        senderId: 2,
        senderName: "Beyza 2",
        color: '#93D033',
        message: "Anim quis nostrud do consequat dolor minim ea esse nulla culpa non fugiat",
        time: "17:04",
        hasSenderName: true,
    },
    {
        date: "15.04.2021",
    },
];